version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: importlib-metadata
    versions:
    - 3.3.0
    - 3.4.0
  - dependency-name: coverage
    versions:
    - 5.3.1
    - "5.4"
  - dependency-name: pytest
    versions:
    - 6.2.1
  - dependency-name: packaging
    versions:
    - "20.8"
  - dependency-name: cffi
    versions:
    - 1.14.4
  - dependency-name: more-itertools
    versions:
    - 8.6.0
