language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"

os:
  - linux
  - windows
  - osx

before_script: pip install -r requirements.txt

script:
  - pytest
  - python tests/test_launch_application.py